# Copyright (c) 2020 极客之道(daogeek.io).
# All rights reserved.
database: mysql

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost/geekshop}
    username: ${MYSQL_USER:geekshop}
    password: ${MYSQL_PASS:geekshop}
    # SQL is written to be idempotent so this is safe
    initialization-mode: always